spring:
  application:
    name: medilab-apps-gateway
  main:
    web-application-type: reactive

  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:5002
          predicates:
            - Path=/api/*

        - id: JournalService
          uri: http://localhost:5003
          predicates:
            - Path=/api/v1.0/events

server:
  port: 5010
logging:
  level:
    org.springframework: DEBUG



#Actuator health check
management:
  endpoints:
    web:
      exposure:
        include: "*"
medilab:
  authn:
    userinfo:
      endpoint: http://localhost:5004/api/token
